---
title: "EU Research Collaboration Networks"
author: "Joao Martins"
date: "12/2/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(janitor)
library(countrycode)
library(igraph)
library(here)
library(conflicted)
source(here::here("R", "global.R"))
conflict_prefer("filter", "dplyr")

df <- 
  here("data-raw", "cordis-h2020projects.csv") %>%
  read_csv2() %>% 
  clean_names()
```

## Intro

## Data

See `README.md`


```{r cars}
collab <- 
  df %>%
  select(id,
         coordinator_country,
         participant_countries)

## Q: coordinator_country always in list of participant_countries?
if (FALSE) {
collab %>%
  mutate(test = str_detect(participant_countries, coordinator_country)) %>%
  summarise(all(test))
  
} # A: No. Add them to the list of participant countries.
    
collab <- collab %>% 
  unite(country, 
        c("coordinator_country", "participant_countries"), 
        sep = ";", 
        na.rm = TRUE) %>%
  mutate(country = str_split(country, ";")) %>%
  unnest(country) %>%
  filter(country != "NA")

ncountries_pproj <- collab %>% count(id)

country_stats <- collab %>% 
  count(country, sort = TRUE)

country_stats <- country_stats %>%
  mutate(
    iso2c = countrycode(country, "eurostat", "iso2c", nomatch = NA_character_),
    eu28 = countrycode(iso2c, "iso2c", "eu28", nomatch = "Non-EU")
  )

assoc <- c("CH", "NO", "IL", "TR")
country_sel <- 
  country_stats %>%
  filter(eu28 == "EU") %>%
  pull(country) %>%
  c(assoc)
  
year_table <- df %>% 
  select(id, year = start_date) %>%
  mutate(year = str_sub(year, 1, 4)) %>%
  arrange(id)

g_collab <- collab %>% 
  # semi_join(filter(year_table, year == "2015"), by = "id") %>%
  filter(country %in% country_sel) %>%
  df2graph()

vertex_size <- igraph::strength(g_collab)
g <- igraph::simplify(g_collab) # remove self-loops
edge_weight <- igraph::E(g)$weight
lout <- igraph::layout_with_fr(g, weights = edge_weight)
colnames(lout) <- c("x", "y")
vdf <- lout %>% 
  as_tibble() %>%
  mutate(
    country = names(igraph::V(g)),
    weight = vertex_size,
    s = sqrt(weight / 100)
  )

edf <- 
  g %>%
  get.data.frame() %>%
  as_tibble() %>%
  left_join(select(vdf, x:country), by = c("from" = "country")) %>%
  rename(from_x = x, from_y = y) %>%
  left_join(select(vdf, x:country), by = c("to" = "country")) %>%
  rename(to_x = x, to_y = y) %>%
  mutate(s = (weight / 1000)^2) %>%
  filter(s > 1) %>%
  arrange(s)

ggplot() +
  geom_segment(data = edf,
               aes(
                 x = from_x,
                 xend = to_x,
                 y = from_y,
                 yend = to_y,
                 size = s,
                 colour = s
               )) +
  scale_color_gradient(low = "gray95", high = "gray50") + 
  geom_point(data = vdf,
             aes(x, y, size = s),
             colour = "gray50") +
  geom_text_repel(data = vdf, aes(x, y, label = country),
                  bg.color = "white",
                  bg.r = 0.15) +
  theme_bw() +
  theme(
    legend.position = "none",
    axis.title = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.line = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank()
  )

```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
